export default {

    DEPARTURES: {
        FETCHING: 'DEPARTURES_FETCHING',
        FETCHED: 'DEPARTURES_FETCHED',
        FETCH_ERROR: 'DEPARTURES_FETCH_ERROR'
    },
    
    SERVICE: {
        FETCHING: 'SERVICE_FETCHING',
        FETCHED : 'SERVICE_FETCHED',
        FETCH_ERROR: 'SERVICE_FETCH_ERROR'
    }
}
